### ISSUE TITLE
SSL errors when trying to submit queries

### ISSUE THREAD

**Issue by sunildkumar** [groundlight/python-sdk#141]
I was getting errors that look like 
```
Error: HTTPSConnectionPool(host='api.groundlight.ai', port=443): Max retries exceeded with url: /device-api/v1/image-queries?want_async=True&detector_id=det_2ZQmUcJnby32em2dIzFXVFFxvNS (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
``` 
when trying to submit image queries to Groundlight. I eventually figured out the problem - the certificates associated with the python I was using were out of date. 

I observed that my `ca-certificates` package was out of date in conda when I ran `conda export env`. I then updated this package: `conda update ca-certificates`, which fixed the problem.

**Comment by robotrapta** [comment]
Seems like not much we can do about this one.  The `ca-certificates` maintainers' decision not to follow semver makes this particularly annoying, but also pretty universal in the python ecosystem.
