### ISSUE TITLE
Switch from RGB to BGR color order to accept OpenCV images directly in `submit_image_query` 

### ISSUE THREAD

**Issue by robotrapta** [groundlight/python-sdk#34]
Right now we expect images to be in RGB color order if they're passed in as numpy arrays.  (This is what PIL / pillow use.)  But OpenCV uses BGR image format by default.

I suspect that if we get a numpy array, it is a lot more likely to have come from OpenCV than somebody converting a PIL image to a numpy array.  Implying we should expect BGR not RGB.

**Comment by robotrapta** [comment]
Current consensus is that we should make this (breaking) change as part of the SDK v0.8.

**Comment by brandon-groundlight** [comment]
Change made as of v0.8
